/* MARKET AI Academy i18n bridge — shares the global app language (acs_lang). */
(function(){
  const packs={
    uk:{
      'Основы рынка':'Основи ринку','Свечи':'Свічки','Тренд и структура':'Тренд і структура','Уровни':'Рівні','Индикаторы':'Індикатори','Таймфреймы':'Таймфрейми','Риск и психология':'Ризик і психологія','НОВОЕ':'НОВЕ','ИЗУЧЕНО':'ВИВЧЕНО','ПРАКТИКА':'ПРАКТИКА','ПРОВЕРЕНО':'ПЕРЕВІРЕНО',
      'интерактивная карта обучения':'інтерактивна карта навчання','От свечей до самостоятельного анализа':'Від свічок до самостійного аналізу','Изучай рынок по шагам. Здесь прогресс оценивает обучение, а не обещает финансовый результат.':'Вивчай ринок крок за кроком. Тут прогрес оцінює навчання, а не обіцяє фінансовий результат.','Уроки':'Уроки','Доступно':'Доступно','Вселенная Академии':'Всесвіт Академії','Миры списком':'Світи списком','Продолжить':'Продовжити','Экзамен':'Іспит','Тур':'Тур','Старая теория':'Стара теорія','твоя карта обучения':'твоя карта навчання','Вселенная обучения':'Всесвіт навчання','текущего учебного пути завершено.':'поточного навчального шляху завершено.','Интерактивный урок MARKET AI':'Інтерактивний урок MARKET AI','Уроки этого мира ещё готовятся.':'Уроки цього світу ще готуються.','Настройки Академии':'Налаштування Академії','Настройки хранятся локально на устройстве.':'Налаштування зберігаються локально на пристрої.','Анимации':'Анімації','Размер текста':'Розмір тексту','Сейчас':'Зараз','Язык обучения':'Мова навчання','Язык Академии синхронизирован с языком всего MARKET AI.':'Мова Академії синхронізована з мовою всього MARKET AI.'
    },
    en:{
      'Основы рынка':'Market Basics','Свечи':'Candles','Тренд и структура':'Trend & Structure','Уровни':'Levels','Индикаторы':'Indicators','Таймфреймы':'Timeframes','Риск и психология':'Risk & Psychology','НОВОЕ':'NEW','ИЗУЧЕНО':'LEARNED','ПРАКТИКА':'PRACTICE','ПРОВЕРЕНО':'TESTED',
      'интерактивная карта обучения':'interactive learning map','От свечей до самостоятельного анализа':'From candles to independent analysis','Изучай рынок по шагам. Здесь прогресс оценивает обучение, а не обещает финансовый результат.':'Learn the market step by step. Progress measures learning here; it does not promise a financial result.','Уроки':'Lessons','Доступно':'Available','Вселенная Академии':'Academy Universe','Миры списком':'Worlds list','Продолжить':'Continue','Экзамен':'Exam','Тур':'Tour','Старая теория':'Legacy theory','твоя карта обучения':'your learning map','Вселенная обучения':'Learning Universe','текущего учебного пути завершено.':'of the current learning path completed.','Интерактивный урок MARKET AI':'Interactive MARKET AI lesson','Уроки этого мира ещё готовятся.':'Lessons for this world are still being prepared.','Настройки Академии':'Academy Settings','Настройки хранятся локально на устройстве.':'Settings are stored locally on this device.','Анимации':'Animations','Размер текста':'Text size','Сейчас':'Current','Язык обучения':'Learning language','Язык Академии синхронизирован с языком всего MARKET AI.':'Academy language is synchronized with the language of MARKET AI.'
    },
    cs:{
      'Основы рынка':'Základy trhu','Свечи':'Svíčky','Тренд и структура':'Trend a struktura','Уровни':'Úrovně','Индикаторы':'Indikátory','Таймфреймы':'Časové rámce','Риск и психология':'Riziko a psychologie','НОВОЕ':'NOVÉ','ИЗУЧЕНО':'NAUČENO','ПРАКТИКА':'PRAXE','ПРОВЕРЕНО':'OVĚŘENO',
      'интерактивная карта обучения':'interaktivní mapa výuky','От свечей до самостоятельного анализа':'Od svíček k samostatné analýze','Изучай рынок по шагам. Здесь прогресс оценивает обучение, а не обещает финансовый результат.':'Uč se trh krok za krokem. Pokrok zde hodnotí učení, ne slib finančního výsledku.','Уроки':'Lekce','Доступно':'Dostupné','Вселенная Академии':'Vesmír Akademie','Миры списком':'Světy v seznamu','Продолжить':'Pokračovat','Экзамен':'Zkouška','Тур':'Prohlídka','Старая теория':'Stará teorie','твоя карта обучения':'tvoje mapa výuky','Вселенная обучения':'Vesmír výuky','текущего учебного пути завершено.':'aktuální výukové cesty dokončeno.','Интерактивный урок MARKET AI':'Interaktivní lekce MARKET AI','Уроки этого мира ещё готовятся.':'Lekce tohoto světa se ještě připravují.','Настройки Академии':'Nastavení Akademie','Настройки хранятся локально на устройстве.':'Nastavení se ukládá lokálně v zařízení.','Анимации':'Animace','Размер текста':'Velikost textu','Сейчас':'Nyní','Язык обучения':'Jazyk výuky','Язык Академии синхронизирован с языком всего MARKET AI.':'Jazyk Akademie je synchronizovaný s jazykem celého MARKET AI.'
    },
    es:{'Основы рынка':'Fundamentos del mercado','Свечи':'Velas','Тренд и структура':'Tendencia y estructura','Уровни':'Niveles','Индикаторы':'Indicadores','Таймфреймы':'Temporalidades','Риск и психология':'Riesgo y psicología','НОВОЕ':'NUEVO','ИЗУЧЕНО':'APRENDIDO','ПРАКТИКА':'PRÁCTICA','ПРОВЕРЕНО':'VERIFICADO','Уроки':'Lecciones','Доступно':'Disponible','Вселенная Академии':'Universo de la Academia','Продолжить':'Continuar','Экзамен':'Examen','Настройки Академии':'Ajustes de la Academia','Язык обучения':'Idioma de aprendizaje'},
    de:{'Основы рынка':'Marktgrundlagen','Свечи':'Kerzen','Тренд и структура':'Trend & Struktur','Уровни':'Niveaus','Индикаторы':'Indikatoren','Таймфреймы':'Zeiteinheiten','Риск и психология':'Risiko & Psychologie','НОВОЕ':'NEU','ИЗУЧЕНО':'GELERNT','ПРАКТИКА':'PRAXIS','ПРОВЕРЕНО':'GEPRÜFT','Уроки':'Lektionen','Доступно':'Verfügbar','Вселенная Академии':'Academy-Universum','Продолжить':'Weiter','Экзамен':'Prüfung','Настройки Академии':'Academy-Einstellungen','Язык обучения':'Lernsprache'}
  };
  try{ if(typeof DICT!=='undefined') Object.entries(packs).forEach(([k,v])=>{DICT[k]=Object.assign(DICT[k]||{},v)}); }catch(_){ }
  function t(s){try{return typeof tr==='function'?tr(s):s}catch(_){return s}}
  function lang(){try{return typeof LANG!=='undefined'?LANG:(localStorage.getItem('acs_lang')||'ru')}catch(_){return 'ru'}}
  function set(code){try{if(typeof setLang==='function')setLang(code);else localStorage.setItem('acs_lang',code)}catch(_){}}
  window.MarketAII18n={t,lang,set,packs};
})();
