/* Checkpoints 22–23 — lightweight Universe foundation + touch camera. No WebGL/3D dependency yet. */
(function(){
 const names={w_basics:'Основы',w_candles:'Свечи',w_trend:'Структура',w_levels:'Уровни',w_indi:'Индикаторы',w_mtf:'Таймфреймы',w_risk:'Риск',w_binary:'Binary'};
 let cam={x:0,y:0,scale:1};
 function progress(id){const ls=LESSONS.filter(l=>l.worldId===id);return ls.length?Math.round(ls.filter(l=>lessonState(l.id).mastery!=='none').length/ls.length*100):0}
 function render(){const host=document.getElementById('acUniverse');if(!host)return;const planets=WORLDS.slice().sort((a,b)=>a.order-b.order).map((w,n)=>{const a=n/WORLDS.length*Math.PI*2,r=118+(n%2)*54,x=Math.cos(a)*r,y=Math.sin(a)*r,p=progress(w.id);return `<button class="acUPlanet" data-world="${w.id}" style="--x:${x}px;--y:${y}px"><span>${w.ic}</span><b>${names[w.id]||w.id}</b><small>${p}%</small><i style="--p:${p}%"></i></button>`}).join('');host.innerHTML=`<div class="acUViewport"><div class="acUCamera"><div class="acUCore"><b>MARKET</b><span>AI</span></div>${planets}</div></div><div class="acUHint">Перетаскивай карту · нажми на планету</div>`;apply();bind(host)}
 function apply(){const c=document.querySelector('#acUniverse .acUCamera');if(c)c.style.transform=`translate(${cam.x}px,${cam.y}px) scale(${cam.scale})`}
 function bind(host){const vp=host.querySelector('.acUViewport');let drag=null,pinch=null;vp.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,cx:cam.x,cy:cam.y};vp.setPointerCapture?.(e.pointerId)});vp.addEventListener('pointermove',e=>{if(!drag)return;cam.x=drag.cx+e.clientX-drag.x;cam.y=drag.cy+e.clientY-drag.y;apply()});vp.addEventListener('pointerup',()=>drag=null);vp.addEventListener('wheel',e=>{e.preventDefault();cam.scale=Math.max(.72,Math.min(1.45,cam.scale+(e.deltaY<0?.08:-.08)));apply()},{passive:false});host.querySelectorAll('.acUPlanet').forEach(b=>b.onclick=e=>{if(Math.abs(cam.x-(drag?.cx||cam.x))>8)return;openAcademyWorld(b.dataset.world)});}
 window.MarketAIUniverse={mount(){cam={x:0,y:0,scale:1};render();setTimeout(()=>window.MarketAIUniverseProgression?.decorate?.(),0)},reset(){cam={x:0,y:0,scale:1};apply()}};
})();
