/* MARKET AI Academy — Candles curriculum */
(function(){
 const C=window.MarketAIAcademy?.Curriculum;if(!C)return;
 const lesson=(id,order,title,subtitle,steps,moduleId='m_anatomy')=>({id,worldId:'w_candles',moduleId,order,icon:'🕯',title,subtitle,difficulty:'beginner',estimatedTime:5,xp:25,prerequisites:[],characterState:'welcome',steps,quiz:[],practice:[],source:'curriculum'});
 const msg=(text,state='explain')=>({type:'character_message',characterState:state,title:'MARKET AI',text});
 const q=(prompt,options,correct,good,bad)=>({type:'multiple_choice',characterState:'question',prompt,options:options.map(([id,label])=>({id,label})),correctAnswer:correct,feedback:{correct:good,incorrect:bad}});
 const lessons=[
 lesson('candles_01_anatomy',10,'Анатомия свечи','Open, High, Low, Close, тело и тени',[msg('Свеча показывает, что происходило с ценой за один выбранный период. Разберём её по частям.','welcome'),{type:'explanation',title:'OHLC',body:'Open — открытие, High — максимум, Low — минимум, Close — закрытие.'},q('Что показывает тело свечи?',[['a','Расстояние между Open и Close'],['b','Только максимум цены'],['c','Только объём']], 'a','Верно: тело связывает открытие и закрытие.','Сравни Open и Close — именно между ними находится тело.'),{type:'summary',text:'Теперь ты знаешь базовую анатомию свечи.'}]),
 lesson('candles_02_direction',20,'Бычья и медвежья свеча','Как читать направление внутри периода',[msg('Цвет — только визуальная подсказка. Главное — где Close относительно Open.'),q('Close выше Open. Какая это свеча?',[['up','Бычья'],['down','Медвежья'],['skip','Определить нельзя']], 'up','Да. Закрытие выше открытия.','Смотри на отношение Close к Open.'),{type:'summary',text:'Направление свечи определяется Open и Close.'}]),
 lesson('candles_03_body_wicks',30,'Тело и тени','Импульс, диапазон и реакция цены',[msg('Большое тело может показывать сильное движение внутри периода, а длинная тень — заметную реакцию от экстремума.'),q('Длинная верхняя тень чаще всего говорит о чём?',[['a','Цена была выше, но отступила от максимума'],['b','Следующая свеча точно упадёт'],['c','Рынок гарантированно развернулся']], 'a','Верно. Это наблюдение о прошедшем движении, не гарантия будущего.','Тень показывает путь цены внутри периода, но сама по себе не предсказывает следующую свечу.'),{type:'summary',text:'Тело и тени читаются только вместе с контекстом.'}]),
 lesson('candles_04_context',40,'Свеча в контексте','Почему одна свеча не является автоматическим сигналом',[msg('Одинаковая свеча у уровня, внутри тренда и в хаотичном диапазоне может иметь разный смысл.','warning'),q('Ты увидел красивую бычью свечу, но структура неясна. Что допустимо сделать?',[['up','Сразу CALL'],['skip','SKIP / NO TRADE'],['down','Обязательно PUT']], 'skip','Да. Отсутствие качественного контекста — нормальная причина пропустить решение.','Одна свеча не обязана быть сигналом. SKIP — полноценное решение.'),{type:'summary',text:'Контекст важнее одной формы свечи.'}],'m_patterns')
 ];
 C.registerSafe('curriculum_candles_v1',{id:'curriculum_candles_v1',version:'1.0.0',worldId:'w_candles',lessons});
})();
