/* MARKET AI V93 integration layer — visual system, strategies, XP, journal/result hooks */
(()=>{'use strict';
 const V93={version:'93.0-preview',markets:['forex','crypto','stocks','otc'],languages:['en','zh','es','hi','pt','ru','fr','de','uk','cs']}; window.MarketAIV93=V93;
 const $=(s,r=document)=>r.querySelector(s);
 function ambient(){if($('#v93Ambient'))return;const h=document.createElement('div');h.id='v93Ambient';h.innerHTML='<canvas></canvas>';document.body.prepend(h);const c=h.firstChild,x=c.getContext('2d');let pts=[];function size(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;pts=Array.from({length:42},(_,i)=>({x:i/41*c.width,y:c.height*(.22+Math.random()*.56)}))}size();addEventListener('resize',size);let t=0;function draw(){t+=.004;x.clearRect(0,0,c.width,c.height);x.strokeStyle='rgba(151,170,194,.09)';x.lineWidth=devicePixelRatio;x.beginPath();pts.forEach((p,i)=>{const yy=p.y+Math.sin(t*3+i*.55)*13*devicePixelRatio+(i? (pts[i-1].y-p.y)*.03:0);i?x.lineTo(p.x,yy):x.moveTo(p.x,yy)});x.stroke();requestAnimationFrame(draw)}if(!matchMedia('(prefers-reduced-motion:reduce)').matches)draw()}
 // Strategy catalog extends the existing V92 engine instead of creating a disconnected selector.
 function strategies(){if(typeof STRATS==='undefined')return;Object.assign(STRATS,{
  trend:{name:'Trend Following',tag:'тренд + структура',desc:'Следование подтверждённому тренду: структура, EMA, сила движения и старший таймфрейм.',mult:{'Тренд EMA':1.9,'Старший таймфрейм':1.8,'Сила тренда':1.7,'Пересечение EMA':1.4,'RSI':.7,'Стохастик':.5}},
  levels:{name:'Support / Resistance',tag:'уровни',desc:'Реакция цены на подтверждённые зоны поддержки и сопротивления с фильтром контекста.',mult:{'Уровень рядом':2.25,'Свечная формация':1.55,'Объём':1.35,'Старший таймфрейм':1.35}},
  breakout:{name:'Breakout + Retest',tag:'пробой и возврат',desc:'Ищет подтверждённый пробой зоны и возврат цены к ней вместо входа в первый импульс.',mult:{'Уровень рядом':2.0,'Объём':1.7,'Сила тренда':1.6,'Старший таймфрейм':1.45,'Фигура графика':1.5}},
  pullback:{name:'Trend Pullback',tag:'откат по тренду',desc:'Вход после контролируемого отката в сторону основного тренда при сохранении структуры.',mult:{'Тренд EMA':1.75,'Уровень рядом':1.65,'Старший таймфрейм':1.6,'RSI':1.15,'Пересечение EMA':1.25}},
  ema:{name:'EMA Trend',tag:'EMA + импульс',desc:'Трендовый профиль на положении и пересечении EMA с обязательной проверкой силы движения.',mult:{'Тренд EMA':2.1,'Пересечение EMA':1.9,'Сила тренда':1.55,'Старший таймфрейм':1.45}},
  rsi:{name:'RSI + Trend Filter',tag:'осциллятор + тренд',desc:'RSI используется только как подтверждение внутри рыночного контекста, а не как одиночная команда.',mult:{'RSI':1.9,'Тренд EMA':1.45,'Старший таймфрейм':1.45,'Сила тренда':1.25}},
  stochastic:{name:'Stochastic Context',tag:'моментум',desc:'Стохастик подтверждает момент входа только при согласии тренда, структуры и уровней.',mult:{'Стохастик':1.9,'Уровень рядом':1.4,'Тренд EMA':1.35,'Старший таймфрейм':1.35}},
  macd:{name:'MACD Momentum',tag:'импульс',desc:'MACD и направление импульса с фильтрацией старшим таймфреймом и структурой.',mult:{'MACD':2.0,'Сила тренда':1.55,'Старший таймфрейм':1.5,'Тренд EMA':1.4}},
  scalping:{name:'Scalping 1–5 min',tag:'короткий горизонт',desc:'Быстрый профиль для 1–5 минут: повышенный фильтр шума, импульса и волатильности.',mult:{'Объём':1.55,'VWAP':1.5,'Сила тренда':1.45,'Свечная формация':1.45,'Уровень рядом':1.4,'Старший таймфрейм':1.3}},
  mtf:{name:'Multi-Timeframe',tag:'несколько ТФ',desc:'Сигнал усиливается только при согласии рабочего и старших таймфреймов.',mult:{'Старший таймфрейм':2.35,'Тренд EMA':1.55,'Сила тренда':1.45,'Уровень рядом':1.35}},
  news:{name:'News / Fundamental',tag:'новости + риск',desc:'Режим контроля новостной волатильности. Без подтверждённых событий не имитирует фундаментальный сигнал.',mult:{'Сила тренда':1.2,'Объём':1.25,'Старший таймфрейм':1.25}}
 });}
 function xp(){const host=$('#lvBox');if(!host||$('.v93XP',host))return;let raw={};try{raw=JSON.parse(localStorage.getItem('acs_edu_v2')||'{}')}catch{}const n=Number(raw.xp||raw.totalXP||0),level=Math.max(1,Math.floor(n/500)+1),base=(level-1)*500,pct=Math.max(0,Math.min(100,(n-base)/500*100));host.insertAdjacentHTML('afterbegin',`<div class="v93XP"><div class="v93XPtop"><b>LEVEL ${level}</b><span>${n} / ${level*500} XP</span></div><div class="v93XPbar"><div class="v93XPfill" style="width:${pct}%"></div></div></div>`)}
 function foldProfile(){const p=$('#profMain');if(!p||p.dataset.v93)return;p.dataset.v93='1';xp();const labels=[...p.querySelectorAll('.lbl2')];for(const lab of labels){const name=lab.textContent.trim();if(!['НАСТРОЙКИ','БОТ'].includes(name))continue;const card=lab.nextElementSibling;if(!card)continue;const wrap=document.createElement('div');wrap.className='v93Fold';wrap.innerHTML=`<button type="button"><span>${name==='НАСТРОЙКИ'?'⚙️ Настройки':'🤖 Бот и приложение'}</span><span class="v93Arrow">›</span></button><div class="v93FoldBody"><div class="v93FoldInner"></div></div>`;lab.replaceWith(wrap);wrap.querySelector('.v93FoldInner').append(card);wrap.firstChild.onclick=()=>wrap.classList.toggle('open')}}
 // Common analysis contract used by future live feeds, signals, journal and Academy exercises.
 V93.analysis={normalize(input={}){return {id:input.id||crypto.randomUUID?.()||String(Date.now()),market:input.market||'forex',asset:input.asset||'',strategy:input.strategy||((typeof STRAT!=='undefined')?STRAT:'multi'),timeframe:input.timeframe||'5m',decision:input.decision||'WAIT',entryWindow:input.entryWindow||null,expiry:input.expiry||null,factors:Array.isArray(input.factors)?input.factors:[],createdAt:input.createdAt||Date.now(),source:input.source||'market-feed'}},shouldTrade(a){return !!a&&['CALL','PUT'].includes(a.decision)&&a.factors.length>0}};
 V93.resultScene=function(result,meta={}){const win=result==='win'||result==='+';return `<div class="v93ResultScene ${win?'v93Win':'v93Loss'}"><div style="font-size:54px">${win?'🏆':'◈'}</div><h3>${win?'Сигнал завершён · +':'Сигнал завершён · −'}</h3><p>${meta.asset||''}${meta.strategy?' · '+meta.strategy:''}</p><button class="btn ghost" onclick="go('history')">Разобрать сделку</button></div>`};
 const LANG={ru:{up:'ВВЕРХ',down:'ВНИЗ',wait:'ЖДАТЬ',noTrade:'НЕ ВХОДИТЬ',journal:'Журнал сделок'},uk:{up:'ВГОРУ',down:'ВНИЗ',wait:'ЧЕКАТИ',noTrade:'НЕ ВХОДИТИ',journal:'Журнал угод'},en:{up:'UP',down:'DOWN',wait:'WAIT',noTrade:'NO TRADE',journal:'Trade Journal'},cs:{up:'NAHORU',down:'DOLŮ',wait:'ČEKAT',noTrade:'NEVSTUPOVAT',journal:'Obchodní deník'}};V93.lang={get(){return localStorage.getItem('market_ai_language')||localStorage.getItem('market_ai_lang')||'ru'},t(k){return (LANG[this.get()]||LANG.ru)[k]||k},supported:V93.languages};
 function init(){ambient();strategies();const obs=new MutationObserver(()=>{if($('#tab-profile.on'))foldProfile()});obs.observe(document.body,{subtree:true,childList:true});if($('#tab-profile.on'))foldProfile();document.documentElement.dataset.marketAi='v93'}
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
