/* MARKET AI V93.1 COMPLETE — integrated experience layer */
(()=>{'use strict';
const V=window.MARKET_AI_V931={version:'93.1',languages:['ru','uk','en','zh','es','hi','pt','fr','de','cs']};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const safe=(f)=>{try{return f()}catch(e){console.warn('[V93.1]',e)}};

/* ---------- 10-language extension of the existing global translator ---------- */
const extraLangs=[['zh','中文','🇨🇳'],['hi','हिन्दी','🇮🇳'],['pt','Português','🇵🇹'],['fr','Français','🇫🇷']];
const packs={
zh:{'Главная':'主页','Сигналы':'信号','Аналитика':'分析','История':'交易日志','Профиль':'个人资料','Журнал':'日志','Журнал сделок':'交易日志','Получить сигнал':'获取信号','Анализировать':'分析','Рынок':'市场','Актив':'资产','Стратегия':'策略','Настройки':'设置','Язык':'语言','Академия':'学院','Обучение':'学习','Мой прогресс':'我的进度','Продолжить обучение':'继续学习','Криптовалюты':'加密货币','Форекс':'外汇','Акции':'股票','Все':'全部','Назад':'返回','Отмена':'取消','Обновить':'刷新','ВВЕРХ':'上涨','ВНИЗ':'下跌','ЖДАТЬ':'等待','НЕ ВХОДИТЬ':'不入场','Сила сигнала':'信号强度','Оптимальный вход':'最佳入场','Экспирация':'到期时间','Уровень':'等级','Результат':'结果'},
hi:{'Главная':'होम','Сигналы':'सिग्नल','Аналитика':'विश्लेषण','История':'ट्रेड जर्नल','Профиль':'प्रोफ़ाइल','Журнал':'जर्नल','Журнал сделок':'ट्रेड जर्नल','Получить сигнал':'सिग्नल लें','Анализировать':'विश्लेषण करें','Рынок':'मार्केट','Актив':'एसेट','Стратегия':'रणनीति','Настройки':'सेटिंग्स','Язык':'भाषा','Академия':'अकादमी','Обучение':'सीखना','Мой прогресс':'मेरी प्रगति','Продолжить обучение':'सीखना जारी रखें','Криптовалюты':'क्रिप्टो','Форекс':'फॉरेक्स','Акции':'स्टॉक्स','Все':'सभी','Назад':'वापस','Отмена':'रद्द करें','Обновить':'रिफ्रेश','ВВЕРХ':'ऊपर','ВНИЗ':'नीचे','ЖДАТЬ':'प्रतीक्षा','НЕ ВХОДИТЬ':'ट्रेड नहीं','Сила сигнала':'सिग्नल शक्ति','Оптимальный вход':'सर्वोत्तम एंट्री','Экспирация':'एक्सपायरी','Уровень':'लेवल','Результат':'परिणाम'},
pt:{'Главная':'Início','Сигналы':'Sinais','Аналитика':'Análises','История':'Diário','Профиль':'Perfil','Журнал':'Diário','Журнал сделок':'Diário de trades','Получить сигнал':'Obter sinal','Анализировать':'Analisar','Рынок':'Mercado','Актив':'Ativo','Стратегия':'Estratégia','Настройки':'Configurações','Язык':'Idioma','Академия':'Academia','Обучение':'Aprender','Мой прогресс':'Meu progresso','Продолжить обучение':'Continuar aprendendo','Криптовалюты':'Cripto','Форекс':'Forex','Акции':'Ações','Все':'Tudo','Назад':'Voltar','Отмена':'Cancelar','Обновить':'Atualizar','ВВЕРХ':'PARA CIMA','ВНИЗ':'PARA BAIXO','ЖДАТЬ':'AGUARDAR','НЕ ВХОДИТЬ':'NÃO ENTRAR','Сила сигнала':'Força do sinal','Оптимальный вход':'Entrada ideal','Экспирация':'Expiração','Уровень':'Nível','Результат':'Resultado'},
fr:{'Главная':'Accueil','Сигналы':'Signaux','Аналитика':'Analyses','История':'Journal','Профиль':'Profil','Журнал':'Journal','Журнал сделок':'Journal de trades','Получить сигнал':'Obtenir un signal','Анализировать':'Analyser','Рынок':'Marché','Актив':'Actif','Стратегия':'Stratégie','Настройки':'Réglages','Язык':'Langue','Академия':'Académie','Обучение':'Apprendre','Мой прогресс':'Ma progression','Продолжить обучение':'Continuer','Криптовалюты':'Crypto','Форекс':'Forex','Акции':'Actions','Все':'Tout','Назад':'Retour','Отмена':'Annuler','Обновить':'Actualiser','ВВЕРХ':'HAUSSE','ВНИЗ':'BAISSE','ЖДАТЬ':'ATTENDRE','НЕ ВХОДИТЬ':'NE PAS ENTRER','Сила сигнала':'Force du signal','Оптимальный вход':'Entrée optimale','Экспирация':'Expiration','Уровень':'Niveau','Результат':'Résultat'}};
safe(()=>{extraLangs.forEach(x=>{if(!LANGS.some(y=>y[0]===x[0]))LANGS.push(x)});Object.assign(DICT,packs)});

const UI={ru:{markets:'РЫНКИ',marketSub:'Forex · Crypto · Stocks · OTC',engine:'MARKET AI · ANALYSIS ENGINE',engineSub:'Один движок связывает рынок, стратегию, сигнал и журнал',choose:'Выбрать сигнал',journal:'Журнал сделок',academy:'MARKET AI ACADEMY',progress:'Мой прогресс',continue:'Продолжить обучение',settings:'Настройки',bot:'Бот и приложение',strategy:'Стратегии анализа',strategyHelp:'Стратегия меняет веса факторов движка. Если подтверждений недостаточно — MARKET AI показывает ЖДАТЬ / НЕ ВХОДИТЬ.',stages:['Структура','Тренд','Уровни','Индикаторы','Стратегия','Финальная проверка']},
uk:{markets:'РИНКИ',marketSub:'Forex · Crypto · Stocks · OTC',engine:'MARKET AI · РУШІЙ АНАЛІЗУ',engineSub:'Єдиний рушій пов’язує ринок, стратегію, сигнал і журнал',choose:'Обрати сигнал',journal:'Журнал угод',academy:'MARKET AI ACADEMY',progress:'Мій прогрес',continue:'Продовжити навчання',settings:'Налаштування',bot:'Бот і застосунок',strategy:'Стратегії аналізу',strategyHelp:'Стратегія змінює вагу факторів. Якщо підтверджень недостатньо — MARKET AI показує ЧЕКАТИ / НЕ ВХОДИТИ.',stages:['Структура','Тренд','Рівні','Індикатори','Стратегія','Фінальна перевірка']},
en:{markets:'MARKETS',marketSub:'Forex · Crypto · Stocks · OTC',engine:'MARKET AI · ANALYSIS ENGINE',engineSub:'One engine connects market, strategy, signal and journal',choose:'Choose signal',journal:'Trade Journal',academy:'MARKET AI ACADEMY',progress:'My progress',continue:'Continue learning',settings:'Settings',bot:'Bot & app',strategy:'Analysis strategies',strategyHelp:'A strategy changes factor weights. If confirmation is weak, MARKET AI returns WAIT / NO TRADE.',stages:['Structure','Trend','Levels','Indicators','Strategy','Final check']}};
function lang(){safe(()=>{if(typeof LANG!=='undefined')localStorage.setItem('market_ai_language',LANG)});return safe(()=>LANG)||localStorage.getItem('acs_lang')||'ru'}
function u(){return UI[lang()]||UI.en}
function dir(d){const L=lang();const m={ru:{CALL:'ВВЕРХ',PUT:'ВНИЗ',WAIT:'ЖДАТЬ'},uk:{CALL:'ВГОРУ',PUT:'ВНИЗ',WAIT:'ЧЕКАТИ'},en:{CALL:'UP',PUT:'DOWN',WAIT:'WAIT'},zh:{CALL:'上涨',PUT:'下跌',WAIT:'等待'},hi:{CALL:'ऊपर',PUT:'नीचे',WAIT:'प्रतीक्षा'},pt:{CALL:'PARA CIMA',PUT:'PARA BAIXO',WAIT:'AGUARDAR'},fr:{CALL:'HAUSSE',PUT:'BAISSE',WAIT:'ATTENDRE'},de:{CALL:'AUFWÄRTS',PUT:'ABWÄRTS',WAIT:'WARTEN'},es:{CALL:'ARRIBA',PUT:'ABAJO',WAIT:'ESPERAR'},cs:{CALL:'NAHORU',PUT:'DOLŮ',WAIT:'ČEKAT'}};return (m[L]||m.en)[d]||d}

/* ---------- unified premium ambient market background ---------- */
function ambient(){if($('#v931Ambient'))return;const el=document.createElement('div');el.id='v931Ambient';el.innerHTML='<canvas></canvas><div class="v931Glow"></div>';document.body.prepend(el);if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;const c=$('canvas',el),x=c.getContext('2d');let pts=[];function rs(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;pts=Array.from({length:34},(_,i)=>({x:i*c.width/33,y:c.height*(.25+Math.random()*.42)}))}rs();addEventListener('resize',rs);let t=0;function draw(){t+=.005;x.clearRect(0,0,c.width,c.height);x.strokeStyle='rgba(160,181,205,.09)';x.lineWidth=devicePixelRatio;x.beginPath();pts.forEach((p,i)=>{const yy=p.y+Math.sin(t*4+i*.48)*20*devicePixelRatio+(i? (pts[i-1].y-p.y)*.025:0);i?x.lineTo(p.x,yy):x.moveTo(p.x,yy)});x.stroke();requestAnimationFrame(draw)}draw()}

/* ---------- visible V93.1 home cockpit ---------- */
function cockpit(){const home=$('#tab-home');if(!home||$('#v931Cockpit'))return;const box=document.createElement('div');box.id='v931Cockpit';box.innerHTML=`<section class="v931Hero"><div class="v931Eyebrow">${u().engine}</div><h2>MARKET AI <span>V93.1</span></h2><p>${u().engineSub}</p><div class="v931MarketRail"><button onclick="window.V931Market('forex')">FX <small>FOREX</small></button><button onclick="window.V931Market('crypto')">₿ <small>CRYPTO</small></button><button onclick="window.V931Market('stocks')">▥ <small>STOCKS</small></button><button onclick="window.V931Market('otc')">OTC <small>OTC</small></button></div><div class="v931Actions"><button class="primary" onclick="go('home');setTimeout(()=>document.querySelector('#sigMkt')?.scrollIntoView({behavior:'smooth'}),80)">⌁ ${u().choose}</button><button onclick="go('history')">▤ ${u().journal}</button></div></section><section class="v931Engine"><div class="v931EngineHead"><span class="pulse"></span><b>ANALYSIS ENGINE</b><small>${safe(()=>STRATS[STRAT].name)||'Multi-analysis'}</small></div><div class="v931Stages">${u().stages.map((s,i)=>`<span style="--i:${i}"><i></i>${s}</span>`).join('')}</div></section>`;home.prepend(box)}
window.V931Market=(m)=>{if(m==='stocks'){toast?.('Stocks','Категория готова к подключению источника котировок. Фиктивные данные не используются.');return}safe(()=>{if(REG?.[m]?.length){S.cat=m;S.asset=REG[m][0].id;sigSyncHead();renderStartPanel?.();toast?.('Рынок',m.toUpperCase(),1)}else toast?.('Источник данных',m.toUpperCase()+' пока без доступных инструментов.')})};

/* ---------- strategy engine integration + visible catalog ---------- */
function strategies(){safe(()=>Object.assign(STRATS,{trend:{name:'Trend Following',tag:'trend + structure',desc:'Структура, EMA, сила движения и подтверждение старшего ТФ.',mult:{'Тренд EMA':1.9,'Старший таймфрейм':1.8,'Сила тренда':1.7,'Пересечение EMA':1.4,'RSI':.7}},levels:{name:'Support / Resistance',tag:'levels',desc:'Реакция цены на подтверждённые зоны с фильтром контекста.',mult:{'Уровень рядом':2.25,'Свечная формация':1.55,'Объём':1.35,'Старший таймфрейм':1.35}},breakout:{name:'Breakout + Retest',tag:'breakout',desc:'Подтверждённый пробой и возврат к зоне вместо входа в первый импульс.',mult:{'Уровень рядом':2,'Объём':1.7,'Сила тренда':1.6,'Старший таймфрейм':1.45,'Фигура графика':1.5}},pullback:{name:'Trend Pullback',tag:'pullback',desc:'Контролируемый откат в сторону основного тренда.',mult:{'Тренд EMA':1.75,'Уровень рядом':1.65,'Старший таймфрейм':1.6,'RSI':1.15}},ema:{name:'EMA Trend',tag:'EMA',desc:'EMA + импульс + обязательная проверка силы движения.',mult:{'Тренд EMA':2.1,'Пересечение EMA':1.9,'Сила тренда':1.55,'Старший таймфрейм':1.45}},rsi:{name:'RSI + Trend Filter',tag:'RSI',desc:'RSI только как подтверждение внутри трендового контекста.',mult:{'RSI':1.9,'Тренд EMA':1.45,'Старший таймфрейм':1.45}},stochastic:{name:'Stochastic Context',tag:'momentum',desc:'Стохастик подтверждает момент входа при согласии структуры и уровней.',mult:{'Стохастик':1.9,'Уровень рядом':1.4,'Тренд EMA':1.35,'Старший таймфрейм':1.35}},macd:{name:'MACD Momentum',tag:'MACD',desc:'MACD и импульс с фильтром старшего таймфрейма.',mult:{'MACD':2,'Сила тренда':1.55,'Старший таймфрейм':1.5}},scalping:{name:'Scalping 1–5 min',tag:'1–5 min',desc:'Короткий горизонт с усиленным фильтром шума и волатильности.',mult:{'Объём':1.55,'VWAP':1.5,'Сила тренда':1.45,'Свечная формация':1.45,'Уровень рядом':1.4}},mtf:{name:'Multi-Timeframe',tag:'MTF',desc:'Усиление только при согласии рабочего и старших таймфреймов.',mult:{'Старший таймфрейм':2.35,'Тренд EMA':1.55,'Сила тренда':1.45}},news:{name:'News / Fundamental',tag:'news risk',desc:'Контроль новостной волатильности; без подтверждённого события не имитирует фундаментальный сигнал.',mult:{'Сила тренда':1.2,'Объём':1.25,'Старший таймфрейм':1.25}}}))}
function strategyPanel(){const p=$('#profMain');if(!p||$('#v931Strategy'))return;const sec=document.createElement('section');sec.id='v931Strategy';sec.className='v931Section';sec.innerHTML=`<div class="v931Title"><div><small>AI PROFILE</small><b>${u().strategy}</b></div><span>›</span></div><p>${u().strategyHelp}</p><div class="v931Strats">${safe(()=>Object.entries(STRATS).map(([k,v])=>`<button class="${k===STRAT?'on':''}" onclick="setStrat('${k}');setTimeout(()=>window.V931RefreshProfile(),20)"><b>${v.name}</b><small>${v.tag}</small></button>`).join(''))||''}</div>`;p.append(sec)}
window.V931RefreshProfile=()=>{const x=$('#v931Strategy');if(x)x.remove();strategyPanel()};

/* ---------- XP / profile / collapsible controls ---------- */
function xpData(){let a={};safe(()=>a=JSON.parse(localStorage.getItem('acs_edu_v2')||'{}'));const n=Number(a.xp||a.totalXP||0),lv=Math.floor(n/500)+1;return {n,lv,pct:(n%500)/5}}
function profile(){const p=$('#profMain');if(!p)return;const x=xpData();if(!$('#v931ProfileTop')){p.insertAdjacentHTML('afterbegin',`<section id="v931ProfileTop" class="v931Profile"><div class="v931Avatar">AI</div><div><small>MARKET AI PROFILE</small><h2>LEVEL ${x.lv}</h2><div class="v931Xp"><i style="width:${x.pct}%"></i></div><span>${x.n} XP · ${500-(x.n%500)} XP → LEVEL ${x.lv+1}</span></div></section><div class="v931ProfileActions"><button onclick="openEdu?.()">🎓 ${u().continue}</button><button onclick="openEdu?.()">◎ ${u().progress}</button></div>`)}strategyPanel();foldProfile()}
function foldProfile(){const p=$('#profMain');if(!p)return;$$('.lbl2,.sect',p).forEach(l=>{const tx=l.textContent.trim().toUpperCase();if(l.dataset.v931||(!tx.includes('НАСТРО')&&!tx.includes('БОТ')))return;l.dataset.v931='1';const card=l.nextElementSibling;if(!card)return;const wrap=document.createElement('div');wrap.className='v931Fold';const name=tx.includes('НАСТРО')?`⚙️ ${u().settings}`:`🤖 ${u().bot}`;l.replaceWith(wrap);wrap.innerHTML=`<button>${name}<span>›</span></button><div class="body"></div>`;wrap.querySelector('.body').append(card);wrap.firstChild.onclick=()=>wrap.classList.toggle('open')})}

/* ---------- Academy: same environment, contextual living terminal ---------- */
function academy(){const tab=$('#tab-education');if(!tab)return;document.body.classList.toggle('v931Academy',$('#tab-education.on')!=null);if($('#v931AcademyHead',tab))return;tab.insertAdjacentHTML('afterbegin',`<section id="v931AcademyHead" class="v931AcademyHead"><div><small>LEARN · PRACTICE · UNDERSTAND</small><h2>${u().academy}</h2><p>Свечи, структура, уровни и стратегии используют тот же язык анализа, что и MARKET AI Engine.</p></div><div class="v931EduChart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></section>`)}

/* ---------- Journal empty state + user-facing terminology ---------- */
function journal(){const list=$('#hList');if(!list)return;const empty=!safe(()=>history.length);if(empty){list.innerHTML=`<section class="v931Empty"><div class="v931Mascot"><div class="head">AI</div><div class="body"></div></div><h3>${u().journal}</h3><p>Здесь появятся только ваши реальные сигналы и результаты. MARKET AI сохранит стратегию, факторы анализа, окно входа и экспирацию.</p><div><button onclick="openEdu?.()">🎓 ${u().continue}</button><button class="primary" onclick="go('home')">⌁ ${u().choose}</button></div></section>`}}
function terminology(root=document){$$('*',root).forEach(el=>{if(el.children.length||['SCRIPT','STYLE'].includes(el.tagName))return;const t=el.textContent.trim();if(t==='CALL'||t==='↗ CALL')el.textContent=(t.startsWith('↗')?'↗ ':'')+dir('CALL');if(t==='PUT'||t==='↘ PUT')el.textContent=(t.startsWith('↘')?'↘ ':'')+dir('PUT');if(t==='WAIT'||t==='◷ WAIT')el.textContent=(t.startsWith('◷')?'◷ ':'')+dir('WAIT')})}

/* ---------- result scenes, tied to actual settled journal results ---------- */
V.resultScene=(r,s={})=>{const win=r==='win'||r==='+';return `<section class="v931Result ${win?'win':'loss'}"><div class="v931ResultArt">${win?'<div class="cup">★<i>$</i></div>':'<div class="sadAI"><b>AI</b><i>−</i></div>'}</div><h2>${win?'Сигнал завершён · +':'Сигнал завершён · −'}</h2><p>${s.sym||''} · ${safe(()=>STRATS[STRAT].name)||''}</p><button onclick="go('history')">${win?'Посмотреть анализ':'Разобрать сделку'}</button></section>`};
let seen=new Set();function detectResults(){safe(()=>history.forEach(h=>{if(!['win','loss'].includes(h.result)||seen.has(h.id))return;seen.add(h.id);if(Date.now()-(h.ts||0)>15*60*1000)return;const host=$('#sigStart')||$('#tab-home .wrap')||$('#tab-home');if(host){const old=$('#v931ResultNow');if(old)old.remove();const d=document.createElement('div');d.id='v931ResultNow';d.innerHTML=V.resultScene(h.result,h);host.prepend(d)}}))}

/* ---------- shared analysis contract ---------- */
V.analysis={normalize(o={}){return {id:o.id||String(Date.now()),market:o.market||safe(()=>S.cat)||'forex',asset:o.asset||safe(()=>S.asset)||'',strategy:o.strategy||safe(()=>STRAT)||'multi',timeframe:o.timeframe||safe(()=>S.tf)||'5m',decision:o.decision||'WAIT',entryWindow:o.entryWindow||null,expiry:o.expiry||null,factors:Array.isArray(o.factors)?o.factors:[],createdAt:o.createdAt||Date.now(),source:o.source||'market-feed'}},shouldTrade(a){return !!a&&['CALL','PUT'].includes(a.decision)&&a.factors.length>0}};

/* ---------- integrate with existing navigation/renderers ---------- */
function hook(){strategies();safe(()=>{const oldRP=window.renderProfile;window.renderProfile=function(){const r=oldRP?.apply(this,arguments);setTimeout(profile,0);return r}});safe(()=>{const oldRH=window.renderHistory;window.renderHistory=function(){const r=oldRH?.apply(this,arguments);setTimeout(()=>{journal();terminology($('#tab-history'));detectResults()},0);return r}});safe(()=>{const oldGo=window.go;window.go=function(t){const r=oldGo?.apply(this,arguments);setTimeout(()=>{document.body.dataset.v931Tab=t;if(t==='home')cockpit();if(t==='profile')profile();if(t==='history')journal();if(t==='education')academy();terminology();},0);return r}})}
function init(){document.documentElement.dataset.marketAi='v931';ambient();hook();cockpit();academy();terminology();const mo=new MutationObserver(()=>{clearTimeout(V._m);V._m=setTimeout(()=>{terminology();if($('#tab-profile.on'))profile();if($('#tab-history.on'))journal();if($('#tab-education.on'))academy();detectResults()},80)});mo.observe(document.body,{subtree:true,childList:true});setInterval(detectResults,3000)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
